# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapisy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapisy',
            name='your_choice',
            field=models.ForeignKey(db_column='title', on_delete=django.db.models.deletion.CASCADE, to='zajecia.Zajecia'),
        ),
    ]
